name: Verify Code Style Workflow

on:
  workflow_call:
    inputs:
        dotnetVersion:
          description: The version of .NET to install onto the runner.
          default: 7.0.x
          type: string
        solutionFile:
          description: The path to the solution file to perform `dotnet build` on. Ex. `./src/MySolution.sln`.
          type: string

jobs:
  verifyCodeStyleJob:
    name: Verify Code Style
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnetVersion }}

      - name: Verify Code Formatting
        run: dotnet format ${{ inputs.solutionFile }} --severity info --verify-no-changes
