name: GitVersion Workflow

on:
  workflow_call:
    outputs:
      major:
        value: ${{ jobs.gitVersionJob.outputs.major }}
      minor:
        value: ${{ jobs.gitVersionJob.outputs.minor }}
      patch:
        value: ${{ jobs.gitVersionJob.outputs.patch }}
      majorMinor:
        value: ${{ jobs.gitVersionJob.outputs.majorMinor }}
      releaseLabel:
        value: ${{ jobs.gitVersionJob.outputs.releaseLabel }}
      majorMinorReleaseLabel:
        value: ${{ jobs.gitVersionJob.outputs.majorMinorReleaseLabel }}
      majorReleaseLabel:
        value: ${{ jobs.gitVersionJob.outputs.majorReleaseLabel }}
      semVer:
        value: ${{ jobs.gitVersionJob.outputs.semver }}
      shortSha:
        value: ${{ jobs.gitVersionJob.outputs.shortSha }}

jobs:
  gitVersionJob:
    name: Run GitVersion
    runs-on: ubuntu-latest
    outputs:
      major: ${{ steps.execute-gitversion-step.outputs.major }}
      minor: ${{ steps.execute-gitversion-step.outputs.minor }}
      patch: ${{ steps.execute-gitversion-step.outputs.patch }}
      majorMinor: ${{ steps.execute-gitversion-step.outputs.major }}.${{ steps.execute-gitversion-step.outputs.minor }}
      releaseLabel: ${{ steps.execute-gitversion-step.outputs.major }}.${{ steps.execute-gitversion-step.outputs.minor }}.${{ steps.execute-gitversion-step.outputs.patch }}${{ steps.execute-gitversion-step.outputs.preReleaseTagWithDash }}
      majorMinorReleaseLabel: ${{ steps.execute-gitversion-step.outputs.major }}.${{ steps.execute-gitversion-step.outputs.minor }}${{ steps.execute-gitversion-step.outputs.preReleaseTagWithDash }}
      majorReleaseLabel: ${{ steps.execute-gitversion-step.outputs.major }}${{ steps.execute-gitversion-step.outputs.preReleaseTagWithDash }}
      semVer: ${{ steps.execute-gitversion-step.outputs.semver }}
      shortSha: ${{ steps.execute-gitversion-step.outputs.shortSha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        id: install-gitversion-step
        uses: gittools/actions/gitversion/setup@v3.1.11
        with:
          versionSpec: '5.x'
        
      - name: Execute GitVersion
        id: execute-gitversion-step
        uses: gittools/actions/gitversion/execute@v3.1.11
