name: Tag Repo Workflow

on:
  workflow_call:
    inputs:
      semVer:
        description: The a semantic version value to tag the repository with.
        required: true
        type: string

jobs:
  tagRepoJob:
    name: Create Git Tag
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ inputs.semVer }}',
              sha: context.sha
            })
